module.exports =
    PostStar:'4'
    SITE_USER_LEVEL:'5'

    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    SITE_USER_LEVEL:'5'
    PostStar:'4'
    PostStar:'4'
    SITE_USER_LEVEL:'5'
    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    SITE_USER_LEVEL:'5'
    PostStar:'4'
    PostStar:'4'
    SITE_USER_LEVEL:'5'
    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    PostStar:'4'
    SITE_USER_LEVEL:'5'