enml = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note><div><div><br clear="none"/></div><div><p>我们致力于对接 <strong>创业</strong> 和 <strong>资本</strong> ，帮助靠谱的项目找到靠谱的钱。<br clear="none"/>同时，我们也期待着有更多心怀梦想的一流程序 员的加入。</p><p><br clear="none"/></p><p>===<br clear="none"/></p><div><br clear="none"/></div><div><br clear="none"/></div></div><div>天使汇，<a shape="rect" href="http://angelcrunch.com" target="_blank">angelcrunch.com</a>。<br clear="none"/></div><div>北京，中关村，创业大街路口，天使汇大厦。</div><div><br clear="none"/></div><div><en-media hash="9fb1095b492f5cf539cac264751ac2cd" type="image/jpeg"></en-media></div><div>我们致力于对接 <strong>创业</strong> 和 <strong>资本</strong> ，帮助靠谱的项目找到靠谱的钱。</div><div>同时，也期待着有更多心怀梦想的一流程序员的加入。</div><div><br clear="none"/></div><div>让我们一起来撰写属于我们的时代传奇。</div><div><br clear="none"/></div><div>我们常用到的技术如下：</div><div>前端 CoffeeScript，jQuery， Avalon， FIS    </div><div>后端 nodejs ( express.js ) ，mako， plim， gearman，python（ tornado ）</div><div>云引擎 leancloud</div><div>数据库  redis ，mongodb</div><div>运维 docker， supervisor</div><div>开发工具  tmux，vim， hg &amp; hg-git</div><div>   </div><div><div>如果您熟悉以上一种或几种技术，就欢迎投递简历（投递邮箱 : <a shape="rect" href="mailto:noman@798.space" target="_blank">noman@798.space</a> ）。</div><div><br clear="none"/></div><div>我们赞同 《<a shape="rect" href="http://icodeit.org/2015/06/do-we-really-short-for-front-end-developer/" target="_blank">我们真的缺前端工程师吗？</a>》文中的观念。</div><div style="padding-left: 30px;"><br clear="none"/></div><div style="padding-left: 30px;">简而言之，开发者视野应该放开开阔一些。不要将自己局限在某种角色上，不但不要局限在前端/后端开发上，压根就不要局限在开发这种角色本身上，你在系统中，可以是设计师，还可 以是业务分析师。虽然不一定最终要你去转行做BA，或者UX，但是更广阔的视野可以使你更加高效的发挥自己的作用，也可以在和别的角色互动式，快速的了解上下文。</div><div style="padding-left: 30px;"><br clear="none"/></div><div style="padding-left: 30px;">…… …… ……</div><div style="padding-left: 30px;"><br clear="none"/></div><div style="padding-left: 30px;">对学习保持着热情，对解决问题保持着热情，仅此而已。在项目上，如果我发现了问题，我就想办法解决，如果属于知识欠缺，那我就会去学习。我还远远没有到达精通这些技术的地步，但是在工程实践领域，根据<a shape="rect" href="https://en.wikipedia.org/wiki/Pareto_principle" target="_blank">80/20原则</a>，这些粗浅的知识足以解决80%的问题，而另外的20%，我们才真正需要一个专家来帮忙。也就是说，团队里需要有一个能解决20%的问题的前端工程师，而其他的80%的前端工作，应该可以被其他所有的开发 完成，对于后端开发也是一样。</div><div style="padding-left: 30px;"><br clear="none"/></div><div>我们认为，好的工程师，必然不会拘泥于某种固定的角色，而是热衷于学习新的知识，探索未知领域。</div><div><br clear="none"/></div><div>所以，我们特别欢迎那些有产品意识，有设计审美 的 全栈式工程师工程师的加入。</div><div><br clear="none"/></div><div>对，我们想要的就是《<a shape="rect" href="http://vdisk.weibo.com/s/C0fcUgZQl-Zt6" target="_blank">黑客与画家</a>》书中描述的那种有着强烈的创作冲动的hacker。</div><div><br clear="none"/></div><div><pre style="padding-left: 30px;" xml:space="preserve">黑客与画家的共同之处，在于他们都是创作者。与作曲家、建筑师、作家一样，黑客和画家都是试图创作出优秀的作品。他们本质上都不是在做研究，虽然在创作过程中，他们可能会发现一些新技术（那样当然更好）。
</pre><div style="padding-left: 30px;"><br clear="none"/></div></div><div><hr/></div><div><br clear="none"/></div><div>最后，我们同时还进行着一个开源项目</div><div><br clear="none"/></div><div><strong>     798.space - 垂直社区技术解决方案</strong></div><div><br clear="none"/> <br clear="none"/></div><div>目前，基于此搭建的网站有：</div><div><br clear="none"/></div><ul><li><a shape="rect" href="http://alpha.tech2ipo.com" target="_blank">alpha.tech2ipo.com</a></li><li><a shape="rect" href="http://coder.angelcrunch.com" target="_blank">coder.angelcrunch.com</a><br clear="none"/></li></ul><div><br clear="none"/></div><div>也同时欢迎程序员掺和，贡献代码，又或者帮忙撰写文档等等（开源项目，当然可以兼职参与）。</div><div><br clear="none"/></div><div>项目想法见 ： <a shape="rect" href="http://docs.798.space/foreword.html" target="_blank">http://docs.798.space/foreword.html</a></div><div>项目规划见 ： <a shape="rect" href="http://dwz.cn/P6x07" target="_blank">http://dwz.cn/P6x07</a></div><div><br clear="none"/></div><div><hr/></div><div><br clear="none"/></div><div><div>冲锋的号角已经吹响</div><div>我们挥舞着战旗</div><div>向着漫天战火，扬帆启航</div><div><br clear="none"/></div></div><div><br clear="none"/></div></div><div><br clear="none"/></div></div><div><br clear="none"/></div><div><br clear="none"/><br clear="none"/></div></en-note>"""

enml2html = require "./enml"

console.log enml2html enml

